/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuComponente;

import javax.swing.ImageIcon;

/**
 *
 * @author Carlos
 */
public class MenuComponente extends javax.swing.JPanel {

    /**
     * Creates new form MenuComponente
     */
    public MenuComponente() {
        initComponents();
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton17 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(580, 820));
        setPreferredSize(new java.awt.Dimension(580, 820));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("Estudiante1");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 179, 66));

        jToggleButton6.setText("Primero1");
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 179, 66));

        jToggleButton11.setText("Segundo1");
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton11MouseClicked(evt);
            }
        });
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 179, 66));

        jToggleButton2.setText("Estudiante2");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 179, 66));

        jToggleButton7.setText("Primero2");
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton7MouseClicked(evt);
            }
        });
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 179, 66));

        jToggleButton12.setText("Segundo2");
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton12MouseClicked(evt);
            }
        });
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 179, 66));

        jToggleButton3.setText("Estudiante3");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 179, 66));

        jToggleButton8.setText("Primero3");
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 179, 66));

        jToggleButton13.setText("Segundo3");
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton13MouseClicked(evt);
            }
        });
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 179, 66));

        jToggleButton4.setText("Estudiante4");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 179, 66));

        jToggleButton9.setText("Primero4");
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton9MouseClicked(evt);
            }
        });
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        add(jToggleButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 179, 66));

        jToggleButton14.setText("Segundo4");
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton14MouseClicked(evt);
            }
        });
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 179, 66));

        jToggleButton5.setText("Estudiante5");
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 179, 66));

        jToggleButton10.setText("Primero5");
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton10MouseClicked(evt);
            }
        });
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 179, 66));

        jToggleButton15.setText("Segundo5");
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton15MouseClicked(evt);
            }
        });
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 179, 66));

        jToggleButton16.setText("Si");
        jToggleButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton16MouseClicked(evt);
            }
        });
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });
        add(jToggleButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 150, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebida.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 280, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandejavacia.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eoLn49mje0.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, 100));

        jToggleButton17.setText("No");
        jToggleButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton17MouseClicked(evt);
            }
        });
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });
        add(jToggleButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 150, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 270, 210));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Resumen del pedido:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ucolor.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 740, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton17.isSelected() == true)
        {
            jToggleButton16.setSelected(false);
        }
        
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton6.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected() == true)
        {
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton2.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton3.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton4.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton5.setSelected(false);
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton5.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton7.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton6.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton8.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton9.setSelected(false);
            jToggleButton10.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton9.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton10.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton10.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton6.setSelected(false);
            jToggleButton7.setSelected(false);
            jToggleButton8.setSelected(false);
            jToggleButton9.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton11.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton12.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton11.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton13.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton14.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton14.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton15.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton15.isSelected() == true)
        {
            jToggleButton1.setSelected(false);
            jToggleButton2.setSelected(false);
            jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
            jToggleButton5.setSelected(false);
            
            jToggleButton11.setSelected(false);
            jToggleButton12.setSelected(false);
            jToggleButton13.setSelected(false);
            jToggleButton14.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
        
        if(jToggleButton16.isSelected() == true)
        {
            jToggleButton17.setSelected(false);
        }
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton6MouseClicked

    private void jToggleButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton7MouseClicked

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jToggleButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton9MouseClicked

    private void jToggleButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton10MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton10MouseClicked

    private void jToggleButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton11MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton11MouseClicked

    private void jToggleButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton12MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton12MouseClicked

    private void jToggleButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton13MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton13MouseClicked

    private void jToggleButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton14MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton14MouseClicked

    private void jToggleButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton15MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton15MouseClicked

    private void jToggleButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton16MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton16MouseClicked

    private void jToggleButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton17MouseClicked
        // TODO add your handling code here:
        gestorBandeja();
        gestorPedido();
    }//GEN-LAST:event_jToggleButton17MouseClicked

    public void gestorPedido()
    {
        int botones [] = getSelectedButtons();
        boolean estudiante = false;
        boolean estandar = false;
        
        precioTotal = 0;
        
        jTextArea1.setText("");
        
        for(int i=0; i<15; i++)
        {

            if(botones[i] == 1)
            {
                if(i < 5)
                {
                    estudiante = true;
                }
                else
                {
                    estudiante = false;
                }
                
                if(i >= 5 && i < 15)
                {
                    estandar = true;
                }
                else
                {
                    estandar = false;
                }

                if(i < 5)
                {
                    jTextArea1.append(getButtonText(i+1));
                    jTextArea1.append("\n"); 
                }
                else
                {
                    if(i >=5 && i < 10)
                    {
                        jTextArea1.append("Primer plato: "+getButtonText(i+1));
                        jTextArea1.append("\n"); 
                    }
                    else
                    {
                       if(i >= 10)
                       {
                            jTextArea1.append("Segundo plato: "+getButtonText(i+1));
                            jTextArea1.append("\n");   
                       }
                    }
                } 
            }
        }
       
        if(estudiante == true)
        {
            jTextArea1.append("\nMenú estudiante\t4.0€");
            jTextArea1.append("\n");
            precioTotal = precioTotal + 4;
        }
        else
        {
            if(estandar == true)
            {
                jTextArea1.append("\nMenú estandar\t\t4,6€");
                jTextArea1.append("\n");
                precioTotal = precioTotal + 4.6;
            }
        }

        if(botones[15] == 1)
        {
            jTextArea1.append("Bebida\t\t1.0€");
            jTextArea1.append("\n");
            precioTotal = precioTotal + 1;
        }
 
        if(precioTotal != 0)
        {
            jTextArea1.append("Precio total:\t\t"+precioTotal+"€");
        }
    }
    
    public void gestorBandeja()
    {
        int botones [] = getSelectedButtons();
        
        boolean primerPlato = false;
        boolean segundoPlato = false;
        boolean bebida = false;
        boolean menuEstandar = true;
        
        if(botones[15] == 1)
        {
            bebida = true;
        }
        
        
        /*
            Para el menu de estudiante
        */
        
        for(int i=0; i<5;i++)
        {
            
            if(botones[i] == 1)
            {
                if(botones[15] == 1)
                {
                    ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejacompleta.png"));
                    jLabel2.setIcon(imagen);
                }
                else
                {
                    ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejacompletasinbebida.png"));
                    jLabel2.setIcon(imagen);
                }
                
                menuEstandar = false; //En caso de que se haya seleccionado el menu de estudiante evitamos hacer los calculos del menú estadar, ya que son incompatibles
            }
        }
        
        /*
            Para el menu estándar
        */
        
        /*
            Para comprobar si hay un primer plato seleccionado
        */
        
        for(int i=5; i<10;i++)
        {
            if(botones[i] == 1)
            {
                primerPlato = true;
            }
        }
        
        /*
            Para comprobar si hay un segundo plato seleccionado
        */
        
        for(int i=10; i<15;i++)
        {
            if(botones[i] == 1)
            {
                segundoPlato = true;
            }
        }
        
        /*
            Seleccionamos las imagenes correspondientes
        */
        
        
        if(menuEstandar)
        {
            if(primerPlato)
            {
                if(segundoPlato)
                {
                    if(bebida)
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejacompleta.png"));
                        jLabel2.setIcon(imagen);
                    }
                    else
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejacompletasinbebida.png"));
                        jLabel2.setIcon(imagen);
                    }
                }
                else
                {
                    if(bebida)
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejaprimerplatobebida.png"));
                        jLabel2.setIcon(imagen);
                    }
                    else
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejaprimerplato.png"));
                        jLabel2.setIcon(imagen);
                    }
                }
            }
            else
            {
                if(segundoPlato)
                {
                    if(bebida)
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejasegundoplatobebida.png"));
                        jLabel2.setIcon(imagen);
                    }
                    else
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejasegundoplato.png"));
                        jLabel2.setIcon(imagen);
                    }
                }
                else
                {
                    if(bebida)
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejasolobebida.png"));
                        jLabel2.setIcon(imagen);
                    }
                    else
                    {
                        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/bandejavacia.png"));
                        jLabel2.setIcon(imagen);
                    }
                }
            }
        }
    }
    
    public void setButtonText(String texto, int numero)
    {
        switch(numero)
        {
            case(1):
                jToggleButton1.setText(texto);
                break;
            
            case(2):
                jToggleButton2.setText(texto);
                break;
                
             case(3):
                jToggleButton3.setText(texto);
                break;
                
            case(4):
                jToggleButton4.setText(texto);
                break;
                
            case(5):
                jToggleButton5.setText(texto);
                break;
                
            case(6):
                jToggleButton6.setText(texto);
                break;
                
            case(7):
                jToggleButton7.setText(texto);
                break;
                
            case(8):
                jToggleButton8.setText(texto);
                break;
                
            case(9):
                jToggleButton9.setText(texto);
                break;
                
            case(10):
                jToggleButton10.setText(texto);
                break;
            
            case(11):
                jToggleButton11.setText(texto);
                break;
                
            case(12):
                jToggleButton12.setText(texto);
                break;
                
            case(13):
                jToggleButton13.setText(texto);
                break;
               
            case(14):
                jToggleButton14.setText(texto);
                break;
                
            case(15):
                jToggleButton15.setText(texto);
                break;
        }         
    }
    
    public String getButtonText(int numero)
    {
        switch(numero)
        {
            case(1):
                return jToggleButton1.getText();
              
            case(2):
                return jToggleButton2.getText();

             case(3):
                return jToggleButton3.getText();

            case(4):
                return jToggleButton4.getText();

            case(5):
                return jToggleButton5.getText();

            case(6):
                return jToggleButton6.getText();

            case(7):
                return jToggleButton7.getText();

            case(8):
                return jToggleButton8.getText();
 
            case(9):
                return jToggleButton9.getText();
    
            case(10):
                return jToggleButton10.getText();
          
            case(11):
                return jToggleButton11.getText();
         
            case(12):
                return jToggleButton12.getText();
            
            case(13):
                return jToggleButton13.getText();
       
            case(14):
                return jToggleButton14.getText();
           
            case(15):
                return jToggleButton15.getText();
       
        }  
        
        return null;
    }
    
    public int [] getSelectedButtons()
    {
        int botones [] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
        
        if(jToggleButton1.isSelected() == true)
        {
            botones[0] = 1;
        }
        
        if(jToggleButton2.isSelected() == true)
        {
            botones[1] = 1;
        }
        
        if(jToggleButton3.isSelected() == true)
        {
            botones[2] = 1;
        }
        
        if(jToggleButton4.isSelected() == true)
        {
            botones[3] = 1;
        }
        
        if(jToggleButton5.isSelected() == true)
        {
            botones[4] = 1;
        }
        
        if(jToggleButton6.isSelected() == true)
        {
            botones[5] = 1;
        }
        
        if(jToggleButton7.isSelected() == true)
        {
            botones[6] = 1;
        }
        
        if(jToggleButton8.isSelected() == true)
        {
            botones[7] = 1;
        }
        
        if(jToggleButton9.isSelected() == true)
        {
            botones[8] = 1;
        }
        
        if(jToggleButton10.isSelected() == true)
        {
            botones[9] = 1;
        }
        
        if(jToggleButton11.isSelected() == true)
        {
            botones[10] = 1;
        }
        
        if(jToggleButton12.isSelected() == true)
        {
            botones[11] = 1;
        }
        
        if(jToggleButton13.isSelected() == true)
        {
            botones[12] = 1;
        }
        
        if(jToggleButton14.isSelected() == true)
        {
            botones[13] = 1;
        }
        
        if(jToggleButton15.isSelected() == true)
        {
            botones[14] = 1;
        }
        
        if(jToggleButton16.isSelected() == true)
        {
            botones[15] = 1;
        }
        
        if(jToggleButton17.isSelected() == true)
        {
            botones[16] = 1;
        }
        
        return botones;
    }
    
    public String getPedido()
    {
        return jTextArea1.getText();
    }
    
    private double precioTotal = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
